# GitHub Actions Workflow: Deploy Documentation to GitHub Pages

name: Deploy Docs

on:
  push:
    branches:
      - main # Or your default branch for documentation updates

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x # Use a version compatible with MkDocs

      - name: Install MkDocs and Material Theme
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions mermaid2
          # Add any other MkDocs plugins listed in your mkdocs.yml

      - name: Build Documentation
        run: |
          cd docs
          mkdocs build
          # The site will be built into docs/site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          # publish_branch: gh-pages # Default branch for GitHub Pages
          # cname: docs.example.com # If you have a custom domain
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy documentation to GitHub Pages"

